name: deploy-auth

on:
  push:
    branches:
      - main
    paths:
      - 'auth/**'
      
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: cd auth && docker build -t davarski/ticketing-auth .
      - uses: mr-smithers-excellent/docker-build-push@v3
        with:
          image: davarski/ticketing-auth
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save $DIGITALOCEAN_CLUSTER_ID
        env:
          DIGITALOCEAN_CLUSTER_ID: ${{ secrets.DIGITALOCEAN_CLUSTER_ID }}
      - run: kubectl rollout restart deployment auth-depl
